### ISSUE TITLE
Remove .render()

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-jst#1]
Don't need both .compile and .render. Just need one... JSTransformer wraps .render for you if it doesn't exist.

Have .compile is better as it allows pre-compilation when able.

**Comment by tunnckoCore** [comment]
Know that. But when `.render` is provided it's better to use it, than our own render that comes from JSTransformer wrapping.

Look at the code of `jst` and you will understand why. It does some magic. Actually some called "caching".

At all, we can't be sure that `jst` do the job correctly. But we should implement methods that they (engines, `jst`, `mustache` whatever..) provide, because we don't know what they do, as in this case.

**Comment by RobLoach** [comment]
Sounds good with me!
